### ISSUE TITLE
Unable to compile with Hibernate 4.1.7.Final

### ISSUE THREAD

**Issue by rbanikaz** [BriteSnow/snow#4]
Getting Compilation error when compiling with 4.1.7.Final, though it works fine with 4.1.6.Final.

Error:
## [INFO] Compiling 546 source files to /Users/rbanikaz/git/normandy/target/classes
1. ERROR in /Users/rbanikaz/git/normandy/src/main/groovy/com/xad/cms/web/CreativePlatformInterface.groovy (at line 0)
   package com.xad.cms.web
   ^
   The type org.hibernate.SessionFactory cannot be resolved. It is indirectly referenced from required .class files
   ----------
   1 problem (1 error)[INFO] -------------------------------------------------------------
   [ERROR] COMPILATION ERROR : 

Deps:

```
        <dependency>
       <groupId>org.hibernate</groupId>
       <artifactId>hibernate-core</artifactId>
       <version>4.1.7.Final</version>
    </dependency>
        <dependency>
             <groupId>org.hibernate</groupId>
             <artifactId>hibernate-validator</artifactId>
             <version>4.2.0.Final</version>
        </dependency>
        <dependency>
              <groupId>com.britesnow</groupId>
              <artifactId>snow</artifactId>
              <version>2.0.0-SNAPSHOT</version>
         </dependency>
```
